worker_processes auto;

events {
    worker_connections 1024;
}

stream {
    server {
        listen 8883 ssl;
        ssl_certificate /etc/letsencrypt/live/banew.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/banew.duckdns.org/privkey.pem;
        proxy_pass mosquitto:1883;
    }
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name banew.duckdns.org;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name banew.duckdns.org;

        ssl_certificate /etc/letsencrypt/live/banew.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/banew.duckdns.org/privkey.pem;

        # 1. MQTT WebSockets
        location ^~ /mqtt {
            proxy_pass http://mosquitto:9001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        # 2. NODE-RED
        location /nodes/ {
            proxy_pass http://nodered:1880;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 3. JETTY
        location / {
            proxy_pass http://servlets:8080;
            add_header Content-Security-Policy "upgrade-insecure-requests";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 4. VIKUNJA
        location /vikunja/ {
            proxy_pass http://vikunja:3456;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Для SSE (Server-Sent Events) і websockets
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 36000s;
        }
    }
}