services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
      - "8883:8883"   # MQTTS (Сертифікати)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - mosquitto
      - nodered
      - servlets
      - vikunja
    networks:
      - app-network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    environment:
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    command: sh -c "mosquitto_passwd -c -b /tmp/passwd $$MQTT_USER $$MQTT_PASSWORD && chown mosquitto:mosquitto /tmp/passwd && exec /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - app-network

  nodered:
    image: nodered/node-red:latest
    container_name: nodered-server
    restart: unless-stopped
    user: "1000"
    environment:
      - NODERED_USER=${NODERED_USER}
      - NODERED_PASSWORD_HASH=${NODERED_PASSWORD_HASH}
    volumes:
      - ./nodered/settings.js:/data/settings.js:ro
      - nodered_data:/data
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  servlets:
    image: jetty:11-jre21
    container_name: lightweight-jetty
    networks:
      - app-network
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=servlet
    volumes:
      - ./webapps:/var/lib/jetty/webapps
    restart: unless-stopped

  pyscripts:
    build: ./pyscripts
    container_name: python-scripts
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      TG_API_ID: ${TG_API_ID}
      TG_API_HASH: ${TG_API_HASH}
      TG_SESSION_STRING: ${TG_SESSION_STRING}
      ANKI_COOKIE: ${ANKI_COOKIE}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      LASTFM_API_KEY: ${LASTFM_API_KEY}
      LASTFM_USER: ${LASTFM_USER}
    networks:
      - app-network

  vikunja:
    image: vikunja/vikunja:latest
    container_name: vikunja
    restart: unless-stopped
    environment:
      VIKUNJA_DATABASE_TYPE: sqlite
      VIKUNJA_DATABASE_PATH: /app/vikunja/files/vikunja.db
      VIKUNJA_SERVICE_PUBLICURL: "https://banew.duckdns.org/vikunja/"
      VIKUNJA_SERVICE_SECRET: ${VIKUNJA_JWT_SECRET}
    volumes:
      - vikunja_data:/app/vikunja/files
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
  mosquitto_data:
  mosquitto_log:
  nodered_data:
  vikunja_data: