# Слухаємо внутрішній трафік від Nginx
listener 1883 0.0.0.0

# Порт для WebSockets (якщо потрібні підключення з браузера)
listener 9001 0.0.0.0
protocol websockets

# ЗАБОРОНЯЄМО анонімний доступ
allow_anonymous false

# Беремо пароль зі згенерованого на льоту файлу
password_file /tmp/passwd

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log