# Слухаємо внутрішній трафік від Nginx
listener 1883 0.0.0.0

# Порт для WebSockets (якщо потрібні підключення з браузера)
listener 9001 0.0.0.0
protocol websockets

# Для тестування дозволяємо без пароля. 
# ПОТІМ ОБОВ'ЯЗКОВО ЗАМІНИТИ НА password_file!
allow_anonymous true 

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log