name: Deploy Server Stack

on:
  push:
    branches:
      - master # або назва твоєї головної гілки
    paths:
      - 'server/**' # Тригер лише при змінах у цій папці

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Запуск деплою через SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/jidai
            
            git fetch origin
            git reset --hard origin/master
            
            cd server
            
            docker compose up -d --build
            
            docker exec nginx-proxy nginx -s reload

            docker image prune -f